import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WebDekey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar */}
        <header style={{ padding: "10px", background: "#333", color: "#fff" }}>
          <h1>WebDekey</h1>
          <nav>
            <a href="/" style={{ marginRight: 10, color: "#fff" }}>Home</a>
            <a href="/products" style={{ color: "#fff" }}>Products</a>
          </nav>
        </header>

        {/* Main content */}
        <main style={{ padding: "20px" }}>{children}</main>

        {/* Footer */}
        <footer
          style={{
            padding: "10px",
            background: "#333",
            color: "#fff",
            marginTop: "20px",
          }}
        >
          &copy; 2025 WebDekey
        </footer>
      </body>
    </html>
  );
}
